(define (make-account balance init-pwd)
  (let ((error-cnt 0)); using internal state
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  ; proc call-the-cops
  (define (call-the-cops)
    (display "cops, here!")
    (newline)
    #f)
  (define (inc-error amount)
    (begin (set! error-cnt (+ error-cnt 1))
           (if (= 3 error-cnt); check error threshold
             (call-the-cops)
             "Incorrect password")))
  (define (dispatch pwd m)
    (cond ((not (eq? pwd init-pwd)) inc-error)
          (else (begin (set! error-cnt 0); right password, then clear error cnt
                       (cond ((eq? m 'withdraw) withdraw)
                             ((eq? m 'deposit) deposit)
                             (else (error "unkown request" m)))))))
  dispatch))

; test code
(define acc (make-account 100 'password))
(display ((acc 'password 'withdraw) 10))
(newline)
(display ((acc 'someother 'deposit) 50))
(newline)
(display ((acc 'someother 'deposit) 50))
(newline)
(display ((acc 'password 'withdraw) 10))
(newline)
(display ((acc 'someother 'deposit) 50))
(newline)
