(define (make-account balance init-pwd)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (error-password amount)
    "Incorrect password")
  (define (dispatch pwd m)
    (cond ((not (eq? pwd init-pwd)) error-password)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "unkown request" m))))
  dispatch)

; 3.7
(define (make-joint account pwd joint-pwd)
  (define (error-password amount)
    "Incorrect password")
  (define (dispatch inputpwd m)
    (cond ((eq? inputpwd joint-pwd) (account pwd m))
          (else error-password)))
  dispatch)

; test code
(define acc (make-account 100 'password))
(display ((acc 'password 'withdraw) 50))
(newline)
(display ((acc 'password 'deposit) 50))
(newline)

(define paul-acc
  (make-joint acc 'password 'jointpwd))
(display ((paul-acc 'jointpwd 'withdraw) 10))
(newline)
(display ((paul-acc 'fakepwd 'withdraw) 10))
(newline)
