(define (make-table same-key?)
  (let ((records '()))
   (define (insert! k v)
     (let ((ret (lookup k)))
      (if (eq? ret #f)
        (set! records (cons (cons k v) records))
        (begin (set-car! ret k) (set-cdr! ret v)))))
   (define (lookup k)
     (define (hlp k rd)
       (cond ((null? rd) #f)
             ((same-key? k (caar rd)) (car rd))
             (else (hlp k (cdr rd)))))
     (hlp k records))
   (define (dispatch m) 
     (cond ((eq? m 'lookup) lookup)
           ((eq? m 'insert!) insert!) 
           (else (error "unkown method" m)))) 
   dispatch))

; test code
(define (appr-same? x0 x1)
  (< (abs (- x0 x1)) 1))

(define *t* (make-table appr-same?))
((*t* 'insert!) 1 'a)
(display ((*t* 'lookup) 1))
(newline)
(display ((*t* 'lookup) 0.9))
(newline)
(display ((*t* 'lookup) 0))
(newline)
((*t* 'insert!) 1.5 'b)
(display ((*t* 'lookup) 1))
(newline)
